version: "3.9"

services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: spring-cloud-learning
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: "%"
      TZ: Asia/Shanghai
    volumes:
      - "./mysql/data:/var/lib/mysql"
      - "./mysql/config:/etc/mysql/conf.d"
    restart: always

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
      - "8080:8080"
    volumes:
      - "./zookeeper/data:/data"
      - "./zookeeper/zoo.cfg:/conf/zoo.cfg"
      - "./zookeeper/logs:/datalog"
    restart: always

  consul:
    image: consul
    ports:
      - "8500:8500"
    command: [agent,-server,-ui,-client=0.0.0.0,-bootstrap-expect=1]
    volumes:
      - "./consul/data:/consul/data"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./rabbitmq/data:/var/lib/rabbitmq"
    restart: always

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: always

  nacos:
    image: nacos/nacos-server:2.0.3
    env_file:
      - ./nacos/env/nacos-standlone-mysql.env
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      - mysql
    restart: always

  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    environment:
      JAVA_OPTS: "-Dserver.port=8858 -Dcsp.sentinel.dashboard.server=localhost:8858 -Dproject.name=sentinel-dashboard"
    ports:
      - "8858:8858"
    volumes:
      - ./sentinel/logs:/root/logs
    restart: always

  seata-server:
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    ports:
      - "8091:8091"
    environment:
      - SEATA_PORT=8091
      # https://github.com/seata/seata/issues/2522
      - SEATA_IP=${DOCKER_IP}
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      # 因为registry.conf中是nacos配置中心，只需要把registry.conf放到./seata-server/config文件夹中
      - "./seata-server:/root/seata-config"
    restart: always
