server:
  port: 84

spring:
  application:
    name: cloud-alibaba-consumer-order-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: localhost:8858
        # 默认8719端口，加入被占用会从8719依次+1扫描，直到找到未被占用的端口
        port: 8719

# 消费者将要去服务的payment服务的url
payment-service:
  nacos-user-service: http://cloud-alibaba-provider-payment-sentinel

# 激活sentinel对Feign的支持
feign:
  sentinel:
    enabled: true