server:
  port: 8001


spring:
  application:
    name: cloud-provider-payment-hystrix

eureka:
  instance:
    # 主机名称
    instance-id: payment-hystrix-8001
    # 访问路径显示IP地址
    prefer-ip-address: true
  client:
    # 是否将自己注册进入EurekaServer，默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认true
    # 单节点无所谓，集群必须设置为true才能配置ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖此地址
      #      defaultZone: http://localhost:7001/eureka    # 单机
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka  # 集群

management:
  endpoints:
    web:
      exposure:
        include: "*"