server:
  port: 9003

spring:
  application:
    name: cloud-alibaba-provider-payment-sentinel
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: "*"